#!/usr/bin/env node
const { execSync } = require('node:child_process');
const { readFileSync, writeFileSync } = require('node:fs');
const { argv } = require('node:process');

const TASK_PREFIX_REGEX = /(\/)(ZU-\d+)/g;
const COMMIT_MESSAGE_REGEX = /^(feature|bug|chore|doc)(\[ZU-\d+\])/
try {
    const [, ,gitCommitMessagePath] = argv
    const commitMessage = readFileSync(gitCommitMessagePath, 'utf8').trim();
    const commitMessageIsValid = COMMIT_MESSAGE_REGEX.test(commitMessage);
    if(commitMessageIsValid) return;

    const branchName = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
    const preparedBranchName = branchName.replace(TASK_PREFIX_REGEX, (taskPrefix, separator, prefix) => `[${prefix}]`);
    const newCommitMessage = `${preparedBranchName}: ${commitMessage}`;
    writeFileSync(gitCommitMessagePath, newCommitMessage)
} catch (err) {
    console.error(`Error: ${err.message}`);
}